version: '3'

services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./logs:/logs
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: always

volumes:
  prometheus_data: {}